### ISSUE TITLE
Appveyor module fails when running in Powershell 6.0

### ISSUE THREAD

**Issue by tomlarse** [RamblingCookieMonster/PSDeploy#109]
I am running this code on Appveyor in Powershell 6.0

```
Deploy DeveloperBuild {
        By AppVeyorModule {
            FromSource $ENV:BHPSModulePath
            To AppVeyor
            WithOptions @{
                Version = $env:APPVEYOR_BUILD_VERSION
            }
        }
    }
```
And it fails with this message
```
Error: 5/3/2018 11:52:03 PM: 
 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: No match was found for the specified search criteria for the provider 'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
```

It works fine in Powershell 5.1

I am guessing that this line is the culprit, running it alone in Powershell 6 generates the same error.
https://github.com/RamblingCookieMonster/PSDeploy/blob/eb25c5afc17b4cbd9e5452e80a0ee99eea97d2ef/PSDeploy/PSDeployScripts/AppVeyorModule.ps1#L156

It seems to me that this line doesn't really do anything in this context, is it really necessary?

**Comment by RamblingCookieMonster** [comment]
Closing this out, thanks again, and ping me if it continues!
