### ISSUE TITLE
should process and should continue

### ISSUE THREAD

**Issue by mgreenegit** [RamblingCookieMonster/PSDeploy#13]
I'm interested in trying to combine the work at lines 149 and 153 of:
https://github.com/RamblingCookieMonster/PSDeploy/blob/dev/PSDeploy/Invoke-PSDeployment.ps1

I believe this could be reduced to a single prompt.  Is this agreeable or does this depart from a design vision?

**Comment by RamblingCookieMonster** [comment]
Makes sense to me!  Patched in 4cc7488
