### ISSUE TITLE
By Filesystem on PS Core fails with error

### ISSUE THREAD

**Issue by ThePoShWolf** [RamblingCookieMonster/PSDeploy#131]
Here is the PSDeploy code:

```powershell
By Filesystem {
    FromSource "Build\ModuleName"
    To "$($env:PSModulePath -split ';' | ?{$_ -like "$($env:USERPROFILE)*" -and $_ -notlike '*vscode*'})\ModuleName\0.0.0"
    Tagged Dev
}
```

Here is the error:

```text
ERROR: Method invocation failed because [System.AppDomain] does not contain a method named 'DefineDynamicAssembly'.
At C:\Users\user\OneDrive\Documents\PowerShell\Modules\PSDeploy\1.0.2\Private\Invoke-Robocopy.ps1:81 char:21
+ ...             $AssemblyBuilder = $Domain.DefineDynamicAssembly($DynAsse ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I've looked up that class in .NET core and it doesn't have that method. I did find a work around: https://stackoverflow.com/questions/36937276/is-there-any-replace-of-assemblybuilder-definedynamicassembly-in-net-core

I'll test and submit a PR with that implemented.

**Comment by RamblingCookieMonster** [comment]
Closing this out, I assume the PR fixed it, but ping me otherwise!  Thanks for spending the time on this, and sorry for the delay!
