### ISSUE TITLE
Exit Codes

### ISSUE THREAD

**Issue by platta** [RamblingCookieMonster/PSDeploy#20]
I'd love to see functionality like Pester's -EnableExit parameter. This is one of the ways Pester can tell CI tools if any of the tests failed. In the same way, CI tools should be able to know if the deployment step failed for some reason.

This would require additional error trapping and things like checking the exit code after calling robocopy.exe.

I'm interested in contributing, but also pretty new to participating in other people's projects, so I figured I'd put this out there to see if there's even interest in including such functionality.

**Comment by RamblingCookieMonster** [comment]
Makes sense to me!  Not something we'd need for our use, but, if folks start contributing, I can certainly see a number of scenarios this could benefit.

I could see an EnableExit parameter on Invoke-PSDeploy as a whole, and perhaps on individual deployments (either Deploy or By functions) in cases where only certain deployments would need the functionality.

Thanks for the reminder... Should probably draft up (/borrow) a contributing.md, if folks end up using and contributing to this!

**Comment by devblackops** [comment]
You can check out my CONTRIBUTING.md for POSHOrigin [here](https://github.com/devblackops/POSHOrigin/blob/master/CONTRIBUTING.md) as an example.

**Comment by platta** [comment]
I spent some time looking through the code. Wanted to get your thoughts on how you want to see things implemented.

It looks like, in general, the code for the individual deployment types will throw an exception in the event of a failure. In my CI test where I integrated PSDeploy, I was copying a folder, so it used robocopy, which does not throw an exception on failure. I think making sure the deployments all behave consistently and throw on any failure is step 1.

After that, it's a question of what the overall behavior should be. When invoking multiple deployments through `Invoke-PSDeploy`, each call to `Invoke-PSDeployment` could be wrapped in a try/catch to prevent one deployment failing from bringing the entire process down (using `Write-Error` in the catch block so it is still visible, just non-terminating). If the `-EnableExit` parameter was specified, we keep track of how many failures we catch and at the end of `Invoke-PSDeploy` call an exit function with that number. An exit code of 0 indicates success, and aside from that the exit code would report how many deployments failed.

I'm going to start working along those lines, but I think this will change some of the existing behavior, which is why I want to hear what you think.

**Comment by gerane** [comment]
Be careful with RoboCopy exitcodes. This is something I'm currently working with in one of my own projects. 

To test this out, start RoboCopy and then kill the process before out finishes. It will still exit with a return code of 1, which is a success exit code for RoboCopy.

I am currently working on a solution that checks the size of the folders to ensure they are the same size. I have this working, but am wanting to add support for excluded folders and files. 

I also created a helper function that just outputs what the codes enumerate to. I'm still tinkering with my project, and it had a different use case than this, but there is some overlap. 

I'm on my phone at the moment, but I'll try to share a few of my ideas tomorrow and get some feedback.

**Comment by gerane** [comment]
With Robocopy, an interesting thing you can do, is rerun the exact same command, but add the /L switch. This will run the same exact command, but won't actually copy the files. If the first command ran the way expected, the /L switch should return Exit Code 0.

**Comment by FooBartn** [comment]
Could we add something like this for now: https://github.com/FooBartn/PSDeploy/blob/master/PSDeploy/Private/Invoke-Robocopy.ps1 ?

I was using this in a psake build script and Jenkins would fail the build every time since, like @gerane said, a successful exit code in robocopy is 1. Technicaly 1, 2, and 4 are "successful". 8 and 10 are actually full out error codes. This doesn't actually check each individual file, but perhaps it's a start?

**Comment by platta** [comment]
I'd say that's better than a start! This is a great wrapper to help us use robocopy like any of the other tools in our PowerShell toolbox.

**Comment by RamblingCookieMonster** [comment]
Hi!

Very cool, thanks for writing that @FooBartn!  It might be worth a slight modification to support @platta's idea of an EnableExit parameter - this would keep things behaving as-is unless someone threw that switch.

For example, rather than exit, you might throw or write-error, which we could catch in PSDeploy and either write the error and continue, or exit if the switch is specified.

Cheers!

**Comment by FooBartn** [comment]
I'll see what I can do :)

**Comment by FooBartn** [comment]
Check now and see if that's closer to what you were looking for. Thanks!

**Comment by RamblingCookieMonster** [comment]
Awesome, looks good to me!  Feel free to submit a PR to master and I can integrate it in, or if you're feeling generous, feel free to add it to `Invoke-PSDeploy`.

Cheers!

**Comment by FooBartn** [comment]
I think I already integrated it correctly. I modified your Filesystem and FilesystemRemote scripts to call Invoke-Robocopy instead of directly calling it. I've been using the version I made for test builds and it seems to be functioning. PR submitted for review

Thanks!

**Comment by FooBartn** [comment]
Since you accepted the pull request, I think you should be able to close this and the backslash issue. Don't know what process you typically follow to validate the issue has been fixed before doing so, though. Let me know if there's anything I can do to help

Thanks!

**Comment by RamblingCookieMonster** [comment]
Makes sense, closing now : ) Thanks!
