### ISSUE TITLE
Organization, Docs, Logo

### ISSUE THREAD

**Issue by RamblingCookieMonster** [RamblingCookieMonster/PSDeploy#23]
- If folks start contributing to this, might be easier to have a separate organization. Created it, just need to migrate and update various links.
- Not a fan of GitHub Wiki (open to all, or open only to collaborators). Will likely spin up a separate docs repo using readthedocs, mkdocs, or github pages, to allow folks to contribute without being given collaborator privileges
- Logo. Or not. It seems like everything has a logo these days. I'm picky, but not very creative. A bad combo for logo design : )

**Comment by michaeltlombardi** [comment]
RE Wiki:
As usual, I'm a fan of mkdocs - it has a builtin ability to deploy to both readthedocs and github pages, too.

I'm not sure an org is necessary but I'm not opposed to the idea either.

**Comment by RamblingCookieMonster** [comment]
Alrighty, moved these to [mkdocs hosted on readthedocs](https://psdeploy.readthedocs.org/), and added notes on contributing.  Thanks!

Yeah, will keep repo here for now.

Going to close this out, docs were the real purpose of this issue.

Thanks!
