### ISSUE TITLE
Idea for Release Notes in PSGalleryModule

### ISSUE THREAD

**Issue by gerane** [RamblingCookieMonster/PSDeploy#37]
I would like to be able to set the ReleaseNotes when publishing. I wanted to offer a suggestion and see what others though and if I was overlooking something. I am new to publishing to the Gallery and about to publish my first, so I wanted to make sure I wasn't overlooking something before going further with the idea. Keith Hill uses something like this in his Publish-Module example template in Plaster.

``` powershell
if ($ReleaseNotesPath) {
    $Params['ReleaseNotes'] = @(Get-Content $ReleaseNotesPath)
}
```

It might require adding a new Environment variable to BuildHelpers or maybe a new param on the PSGalleryModule.ps1. I have not looked that far ahead since I wanted to make sure I wasn't overlooking anything. I know there are some odd issues related to psd1 or similar.

**Comment by gerane** [comment]
You could also just check the ProjectRoot for a CHANGELOG.md or ReleaseNotes.md or something of that nature.

**Comment by RamblingCookieMonster** [comment]
Hi!  Missed this back in June - feel free to ping me if I ever let something go for this long : )

This would definitely be handy, could probably add a DeploymentOption that takes precedence, look for a deterministic path like you mentioned as fall back, ignore if nothing is found?

Cheers!

**Comment by RamblingCookieMonster** [comment]
Just going through old issues - wonder if BuildHelpers would benefit from something like `Get-ReleaseNotes` or `Get-Changelog`, which would use existing function/logic to get module path within repo, extract changelog.  Could potentially include switch or other parameter to control which section of changelog to pull, if this could be done in a reliable way
