### ISSUE TITLE
Get-PSDeployment.PS1 FromSource Can't handle UNC path

### ISSUE THREAD

**Issue by JoArnold** [RamblingCookieMonster/PSDeploy#41]
I discovered when I try to use a UNC path for fromSource it error's out  

My TestProject.PSDeploy.ps1

Deploy UniqueDeploymentName{                        # Deployment name.
    By FileSystem {                                 # Deployment type.
        FromSource '\ServerName\d$\Sandbox\PSDeploy\Workspace\Artifact\SomeFolder'
        To '\ServerName\d$\Sandbox\PSDeploy\Server001\D\App\Somefolder'
        Tagged DevFrontend
        WithOptions @{  
                     Mirror = $True  
                     }
    }
}

The error:

Source            : Microsoft.PowerShell.Core\FileSystem::\ServerName\d$\Sandbox\PSDeploy\Workspace\Artifact\SomeFolder'

This works when I use dot sourcing and local path. I found in Get-PSDeployment.PS1 you are using 
( Resolve-Path $Source ).Path

This is what is adding the Microsoft.PowerShell.Core\FileSystem:: in front of the UNC path. I added this around it to get around it. 

```
                    If ( $Source -like '\\*')
                        {
                        $LocalSource = $Source
                        }
                    Else
                        {
                        $LocalSource = ( Resolve-Path $Source ).Path
                        }
```

I am sure this is a better fix for this but wanted to point this out just in case anyone else was running into this issue.

**Comment by gerane** [comment]
Edit: I see, Markdown escaped the second.

**Comment by JoArnold** [comment]
I should of read through this before hitting submit. This is my first time posting anything on GitHub. I asure you I have 2 \ in my code. It must of removed one of mine.

Deploy UniqueDeploymentName{                        # Deployment name.
    By FileSystem {                                 # Deployment type.
        FromSource '\ServerName\d$\Sandbox\PSDeploy\Workspace\Artifact\SomeFolder'
        To '\stlmidwins04\d$\Sandbox\PSDeploy\Server001\D\App\BusinessAnalytics.API'
        Tagged DevFrontend
        WithOptions @{
                         Mirror = $True
                               }
    }
}

**Comment by RamblingCookieMonster** [comment]
No worries @JoArnold!

@gerane, would your recent change to path handling help with this?  It deployed to PowerShellGallery after or right around the time this was posted, so there's a good chance it was using the previous version.

**Comment by gerane** [comment]
Not in that one, I was only resolving Target directories. I left Source out because I saw you were using Resolve-Path on it earlier in the process. 

I think I have a fix for this.

**Comment by gerane** [comment]
This should resolve UNC, Normal, and PSDrive paths.

``` powershell
$LocalSource = ( Resolve-Path $Source ).ProviderPath
```

**Comment by gerane** [comment]
I don't think this will be an issue in the Remote one, you are converting the Source into a unc with $env:computername injected in with c$

**Comment by JoArnold** [comment]
Excellent fix. Thank you all very much

**Comment by gerane** [comment]
Oh, I think I missed a reference depending on how you are executing the deployments. Realized it when writing some tests.

Just added that fix to the PR
