### ISSUE TITLE
New deployment type proposal: vSphereOVF

### ISSUE THREAD

**Issue by equelin** [RamblingCookieMonster/PSDeploy#51]
Please find below the documentation I've written for a new deployment type `vSphereOVF`. Feel free to give any feedback ! (cc to VMware folks @lamw @alanrenouf) 

Deployment script can be found [here](https://github.com/equelin/PSDeploy/blob/feature-vsphere-ovf/PSDeploy/PSDeployScripts/vSphereOVF.ps1).

---

OVF or OVA are a standard way to package virtual machines. vSphereOVF will allow you to easely deploy an OVF/OVA into a VMware vSPhere infrastructure.
# Prerequisites

Before deploying you'll need to:
- Install VMware PowerCli 
- Connect to a vCenter server or an ESXi server with the command `Connect-VIServer`
# Simple Example

Here is an example deployment config:

``` Powershell
Deploy 'MyOVF' {
    By vSphereOVF {
        FromSource 'C:\MyOVF.ovf'
        To 'esxi.example.com'
        Tagged 'Prod'
        WithOptions @{
            Name = 'VM01'
            Datastore = 'DATASTORE01'
            OvfConfiguration = @{
                'NetworkMapping.VM Network' = 'Production'
            }
            PowerOn = $true
        }
    }
}
```

Let's explain the different parameters:
- `FromSource` specifies the path to the .ovf or .ova file
- `To` specifies the esxi server used as a target
- `Name` specifies the name of the virtual machine
- `Datastore` specifies on wich datastore the VM will be stored. If not provided, the datastore with the largest free space will be selected
- `OvfConfiguration` specifies advanced configurations that will be used to deploy the virtual machine
- `PowerOn` specifies if the virtual machine should be powered on after the deployment
# Real Example

Here is an example to deploy a VMware vCenter Virtual Appliance (VCSA). More specific informations about the automated deployment of a VCSA can be found [here](http://www.virtuallyghetto.com/2015/02/ultimate-automation-guide-to-deploying-vcsa-6-0-part-1-embedded-node.html)  

``` Powershell
Deploy 'VCSA' {
    By vSphereOVF {
        FromSource 'D:\VMware\vSphere\vSphere 6.0\vCenter\VCSA\U2\vmware-vcsa.ova'
        To 'esxi.example.com'
        Tagged 'Prod'
        WithOptions @{
            Name = 'VCENTER' # VM Name
            Datastore = 'SALLE1-DATASTORE02' # Datastore Name
            OvfConfiguration = @{
                'NetworkMapping.Network 1'                = 'Supervision' # vSphere Portgroup Network Mapping
                'DeploymentOption.value'                  = 'tiny' # tiny,small,medium,large,management-tiny,management-small,management-medium,management-large,infrastructure
                'IpAssignment.IpProtocol'                 = 'IPv4' # IP Protocol
                'guestinfo.cis.appliance.net.addr.family' = 'ipv4' # IP Address Family
                'guestinfo.cis.appliance.net.mode'        = 'static' # IP Address Mode
                'guestinfo.cis.appliance.net.addr'        = '192.168.1.2' # IP Address 
                'guestinfo.cis.appliance.net.pnid'        = '192.168.1.2' # IP PNID (same as IP Address if there's no DNS)
                'guestinfo.cis.appliance.net.prefix'      = '24' # IP Network Prefix (CIDR notation)
                'guestinfo.cis.appliance.net.gateway'     = '192.168.1.254' # IP Gateway
                'guestinfo.cis.appliance.net.dns.servers' = '192.168.1.1' # Comma separated list of IP addresses of DNS servers.
                'guestinfo.cis.appliance.ntp.servers'     = '0.pool.ntp.org' # Comma seperated list of hostnames or IP addresses of NTP Servers
                'guestinfo.cis.appliance.root.passwd'     = 'VMware1!' # Root Password
                'guestinfo.cis.appliance.ssh.enabled'     = 'True' # Enable SSH
                'guestinfo.cis.vmdir.domain-name'         = 'vsphere.local' # SSO Domain Name
                'guestinfo.cis.vmdir.site-name'           = 'site01' # SSO Site Name
                'guestinfo.cis.vmdir.password'            = 'VMware1!' # SSO Admin Password
            }
            PowerOn = $true
        }
    }
}
```

**Comment by devblackops** [comment]
Nice. This relates pretty closely with my [POSHOrigin_vSphere](https://github.com/devblackops/POSHOrigin_vSphere) DSC module. OVF/OVA resources are something I've been meaning to add.

**Comment by equelin** [comment]
Thanks @devblackops.  your project seems quiet interesting! Good work!

**Comment by equelin** [comment]
@RamblingCookieMonster Do you mind if I create a repo for gathering psdeploy.ps1 examples for deploying popular OVF/OVA appliances ? Or maybe you have something in mind for the other deployment types ?

**Comment by RamblingCookieMonster** [comment]
Up to you!  If you wanted something more generic, I'd also be up for either of the following as well:
- Adding an Examples folder to the root of the PSDeploy repo, further broken out into deployment type subfolders.  e.g. `PSDeploy\Examples\vSphereOVF\...`, `PSDeploy\Examples\PlatyPS\...`
- Moving to a [PSDeploy organization](https://github.com/psdeploy) where various repos could be grouped together, perhaps including a psdeploy-examples (or some other name) repo

Your own repo, or either of the latter work though, up to you!

Cheers!

**Comment by lamw** [comment]
@equelin You can find quite a few examples here https://github.com/lamw/PowerCLI-Deployment as well as from my blog on past OVF/OVAs. It would be good to get a repo that checks the version of the appliance, as some will have new/updated properties

**Comment by equelin** [comment]
@RamblingCookieMonster Your project, your rules ;-) I'm not really aware of github's organization but it might be a good idea as PSDeploy is gaining more attraction. I Think that a side repo for vSphereOVF might be good if you look at @lamw repository there could be a lot of example !

@lamw That's your blog post that gave me the idea to use PSDeploy for deploying OVF but I was not aware of your repository. I hope you don't mind if I borrow your idea!?
Subfolders for appliance version is a really good idea !

**Comment by RamblingCookieMonster** [comment]
I overcomplicated things : P I think the easiest thing for now would be for you to just create that repo.

Down the line, could move PSDeploy to the psdeploy organization.  If your repo was only related to psdeploy, you could make the transfer as well if you wanted ([existing things](https://help.github.com/articles/about-repository-transfers/#whats-transferred-with-a-repository) shouldn't break). Don't see any compelling reason to transfer things now though.

Very cool idea, so basically a library of recipes for certain deployments?

Cheers!

**Comment by equelin** [comment]
>  just create that repo.

Ok !

> Very cool idea, so basically a library of recipes for certain deployments?

Exactly, I was thinking of simple recipes involving one appliance and perhapes more complicated ones for deploying a complete infrastructure (maybe with Pester and PSake...).

**Comment by equelin** [comment]
Here we go !

https://github.com/equelin/PSDeploy-vSphereOVF-Recipes/tree/develop/Sexibytes/Sexigraf

**Comment by alanrenouf** [comment]
This is cool, love it!

**Comment by RamblingCookieMonster** [comment]
Closing this out, thanks again @equelin!
