### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by LaurentDardenne** [RamblingCookieMonster/PSDeploy#58]
Hi,
in this [file](https://github.com/RamblingCookieMonster/PSDeploy/blob/master/PSDeploy/Public/Deploy.ps1) a bracket is missing :  _Deploy DeployMyModule_

**Comment by RamblingCookieMonster** [comment]
Eek, in both examples, thanks for spotting this!  Want to submit a PR, or shall I just edit?

Cheers!

**Comment by LaurentDardenne** [comment]
_Want to submit a PR,_
No sorry.
