### ISSUE TITLE
Incorrect module version when deploying with PSGalleryModule through CI

### ISSUE THREAD

**Issue by equelin** [RamblingCookieMonster/PSDeploy#59]
I've tried to implement the release pipeline found here http://ramblingcookiemonster.github.io/PSDeploy-Inception/ and I've got an interesting problem.

When I push to my master branch with _!deploy_ in the commit message, everything works well excepted that the module version is not handled properly on the Powershell Gallery. For example, if the version of the module on the gallery is 0.7.0, the next version deployed by the pipeline will be the 0.7.1 no matter what version is in the module manifest...

Any ideas about that?

**Comment by RamblingCookieMonster** [comment]
Hi Erwan!

Yep, you can kill that piece if you'd like, [it's set here](https://github.com/equelin/Unity-Powershell/blob/master/psake.ps1#L65) in the psake `build` task.  I kept forgetting to bump things, ended up just having it automatically bump based on existing gallery version.

Cheers!

**Comment by equelin** [comment]
Hi Warren !
Thx for your reply! So I just have to remove those lines, right?
I'm not sure to understand where those functions comes from? (Get-NextPSGalleryVersion, Update-Metadata)

**Comment by RamblingCookieMonster** [comment]
Ahh, so those are part of [BuildHelpers](https://github.com/RamblingCookieMonster/BuildHelpers) - basically a bunch of little functions that might come in handy for a PowerShell-oriented build.

If you just kill that whole Try/Catch, it won't mess with the version in the PSD1.  Also, note the Set-ModuleFunctions bit right above - that imports your module during the build, reads exported functions, sets these in the psd1 - might not be desired (personally I leave psd1 FunctionsToExport = '*', and let this update in the build, so I don't need to add new public functions manually, but... I might just be lazy).

Side note: Update-Metadata is exposed through BuildHelpers, but is really from Joel Bennett's awesome Configuration module - for whatever reason, publishing with that as a RequiredModule failed things in AppVeyor, so it's just hard coded into the BuildHelpers module now.

Cheers!

**Comment by equelin** [comment]
Thanks for your explanations Warren !
