### ISSUE TITLE
FileSystem deployment of file to non-existing directory throws exception

### ISSUE THREAD

**Issue by csandfeld** [RamblingCookieMonster/PSDeploy#60]
These test deployments ...

``` PowerShell
Deploy Test {
    By FileSystem  {
        FromSource  'test.txt'
        To 'C:\Does\Not\Exist\'
    }
}
```

and

``` PowerShell
Deploy Test {
    By FileSystem  {
        FromSource  'test.txt'
        To 'C:\Does\Not\Exist\test.txt'
    }
}
```

... both throw an exception when the destination folder does not exist, due to limitations of the Copy-Item cmdlet.

One way around the issue

``` PowerShell
Try {

    Copy-Item -Path $Map.Source -Destination $Target -Force

}
Catch [System.IO.IOException] {

    $NewDir = $Target
    if ($NewDir[-1] -ne '\')
    {
        $NewDir = Split-Path -Path $NewDir
    }
    $null = New-Item -ItemType Directory -Path $NewDir
    Copy-Item -Path $Map.Source -Destination $Target -Force

}
```

(opted for the try/catch approach to not have to do a test-path for each file)

I can go ahead and submit a pull request for this, but wanted to run it by you first in case you have reasons for not handling non-existing folders in the first place

**Comment by RamblingCookieMonster** [comment]
Nice find!

Running out of caffeine, but on first look, looks like that should work, feel free to submit a PR!  If there was a reason for not handling it, I certainly don't recall it : )

The FileSystem bit definitely needs some work, or to be split out into different transport types.  @michaeltlombardi had some good ideas, but they've scrolled out of Slack history.

Cheers!

**Comment by csandfeld** [comment]
Thanks Warren.

The [contribution guidelines](https://github.com/RamblingCookieMonster/PSDeploy/blob/master/Contributing.md) state that PR's should be made in the dev branch. The dev branch is quite far behind the master branch - do you still want it in dev, or should I make it against master?

**Comment by RamblingCookieMonster** [comment]
Ahh thanks for the reminder, need to update that - yeah, master for now, sorry about that!
