### ISSUE TITLE
Setup and Cleanup

### ISSUE THREAD

**Issue by RamblingCookieMonster** [RamblingCookieMonster/PSDeploy#7]
Add pester-like Before and After functionality

**Comment by RamblingCookieMonster** [comment]
Any suggestions on naming these?

Existing functions are named as they relate to the deployment:

The deployment is...
- To a target
- From a source
- By a deploymenttype
- DependingOn another deployment

etc.

Following that logic, 'Before' would seem more like a dependency option, or would be inverted:
- This deployment runs Before some other deployment
- This deployment runs Before this scriptblock (i.e. the scriptblock actually runs 'after')

That seems clunky and confusing.

Potential options, without much thought:
- WithSetup, WithTeardown
- WIthSetupScript, WithTeardownScript
- WithPreScript, WithPostScript
- Ignore current conventions, treat before and after as Pester does.

Any input would be appreciated!

**Comment by RamblingCookieMonster** [comment]
Going with WithPreScript and WithPostScript, deployment object property PreScript and Postscript.

Open to alternatives though, seems clunky.

**Comment by michaeltlombardi** [comment]
What about BeginWith and EndWith, deployment object properties of the same? Keeps the Begin, Process, End meaning understood from prior use of PowerShell. 

Not really opposed to PreScript/PostScript though, it's pretty clear what that means too.

**Comment by RamblingCookieMonster** [comment]
Initial implementation in dfe1ef4, some bug fixes in the following commits.

@michaeltlombardi I like that, it does follow with an existing convention.  Unless something better comes up, I think the BeginWith and EndWith are a good option before merging into master

**Comment by RamblingCookieMonster** [comment]
Bah, going to just leave it:
- Name indicates purpose a bit more. 'Script' vs. BeginWith... something?
- Code and tests are already in place
- I'm lazy : )

BeginWithScript / EndWithScript would work for the first bullet, but fail the latter 3 : ) open to PRs if anyone wants to take the time though!

**Comment by michaeltlombardi** [comment]
It's not a massive requirement - the current implementation is clear and sane as-is. This seems like more of a "someday, maybe, if we feel like it" enhancement. There's not really any standardization in this space that I'm aware of.
