### ISSUE TITLE
Invoke-Robocopy not injected in FilesystemRemote

### ISSUE THREAD

**Issue by lyra-edmundson** [RamblingCookieMonster/PSDeploy#70]
PSDeploy version: 0.1.24
Powershell version: 5.1.14393.206
Example:
```
Deploy something {
    By FilesystemRemote {
        FromSource 'C:\testSource'
        To 'C:\testDest'
        WithOptions @{
            ComputerName = 'remoteHost'
        }
    }
}
```

Assuming _remoteHost_ is real and you have credentials, calling Invoke-PSDeploy on this will output:

> The term 'Invoke-Robocopy' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Invoke-Robocopy:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : remoteHost

I was able to fix this by simply adding `'Invoke-Robocopy'` to `$FunctionsToInject` in _PSDeploy/PSDeployScripts/FilesystemRemote.ps1_.

**Comment by lyra-edmundson** [comment]
Sorry if this is already known about, I did a quick search of the existing issues and didn't find anything.

**Comment by RamblingCookieMonster** [comment]
Totally makes sense, poor testing and haven't used that deployment type since the change - thanks for the heads up!

**Comment by RamblingCookieMonster** [comment]
Wrapped up a while ago, closing!
