### ISSUE TITLE
Switch to master + features branches

### ISSUE THREAD

**Issue by RamblingCookieMonster** [RamblingCookieMonster/PSDeploy#73]
Hi!

So, based on the confusion, mostly induced by poor documentation and not swapping the default branch, branches have been a bit of a pain - PRs submitted to both master and dev, and I don't want to scare people off by telling them to switch branches.

Rather than continue to poorly execute rebase/merge operations, or get stricter, I'm trying to think of any downsides to just switching to a master branch + feature branch model, kill the dev branch and adjust documentation.  If you have any concerns over this, hit me up, otherwise, will make the switch tomorrow/Saturday (plenty of time for responses, right? : P)

Cheers!

**Comment by ngetchell** [comment]
I ran into the exact same thing. People issued pull requests on dev when they should have been using master. Feature branches merging into a master branch is just simpler.

**Comment by martin9700** [comment]
But you should be pulling to the dev branch, right?  That's the whole point of a dev branch (which is just a generic feature branch).  When you have enough pulls on dev that you want to go live the owner does a pull from the dev branch to the master?

That's my understanding.

**Comment by RamblingCookieMonster** [comment]
Yep! The problem is that we can't control what branch folks work from, or submit a pull request against - it can be dissuading to them to turn around and say _redo this against dev_.  Particularly if they're new to git or GitHub.

With just prod, there can be no mistakes, and we can accept PRs on demand, no need to accept+merge-to-master-at-some-point.

Cheers!

**Comment by martin9700** [comment]
True, but somehow just doesn't _feel_ right.  I have an open PR to dev, want me to refork off master and resubmit?

**Comment by RamblingCookieMonster** [comment]
Nope! I'l go ahead and merge that, merge dev into master, update contributing references to dev branch, and kill dev branch.

Timing wise, might be next week; a bit busy wrapping up before holiday break during work, and last minute shopping and prep after work.

Cheers!

**Comment by RamblingCookieMonster** [comment]
Deleted and updated docs, we'll work off master now.

I'll try to keep my own commits, barring minor changes (I know...) to branches to avoid any issues - everyone else can treat the fork as a branch, and submit the PR to master.

Cheers!
