### ISSUE TITLE
[Question] Filesystem deployment to file share with credentials

### ISSUE THREAD

**Issue by megamorf** [RamblingCookieMonster/PSDeploy#78]
Hey Warren,

I've had a look at your PSDeploy docs and the actual code for Filesystem deployments and I believe both don't cover my user case. I want to copy a module to a file share as a user that has the required privileges. However my psdeploy script is being run in the context of my Gitlab CI runner which doesn't have access to the share.

The use case is as follows:

```
[Server with Gitlab CI runner] --Contoso\User--> [File server share\modules dir]
```
What would be your recommended approach to implement the copy job? Thanks in advance.

-Sebastian

**Comment by RamblingCookieMonster** [comment]
Hi!

Good question - It's a pretty ugly alternative, but in the past I've used the FileSystemRemote deployment type, which kicks off the same code in a pssession (i.e. allowing you to specify creds, which you can perhaps [inject them](https://docs.gitlab.com/ce/ci/variables/#secret-variables) without hard coding).

Oh.  Yeah.  Ugly, in that double hop can be fun.  We had constrained, delegated endpoints to get around that.  I know.  Ugly.

What version of PowerShell do you have?  Wonder if a deploymenttype that uses `Copy-Item -ToSession` would help, and avoid the nonsense above?

Cheers!

**Comment by megamorf** [comment]
We run PSv5 and are about to roll out 5.1. The File server is a non-Windows system (NetApp) so `-ToSession` isn't going to work in this case. Copy-Item with credentials seems to be problematic - a quick google search suggested `Start-BitsTransfer -Credential` as a working alternative or New-PSDrive. 

That could complicate the current simple FileSystem approach :(

**Comment by megamorf** [comment]
I've checked `Start-BitsTransfer` and it looks like it doesn't fit the use case. The Cmdlet only runs in interactive sessions and its Credential parameter is broken (See [StackOverflow](http://stackoverflow.com/questions/22457548/bits-transfer-file-with-multi-domain). An alternative approach would be to use New-PsDrive. 

:-1:
