### ISSUE TITLE
[Question] -WhatIf passed to Invoke-PSDeploy for FileSystem deployment

### ISSUE THREAD

**Issue by rbernardino** [RamblingCookieMonster/PSDeploy#80]
Hello Warren,

Any thoughts on if I passed -WhatIf to Invoke-PsDeploy and I've got an FS deployment will also show a preview of what will actually happen? Kinda test run. I believe it's similar to passing /L to Robocopy? 

Thank you!

**Comment by RamblingCookieMonster** [comment]
@rbernardino interesting!  It definitely won't do it today - IIRC it will just spit out the deployment details (type, source, target, etc.), but won't expand things to say what will actually change when that's invoked.  Would be cools to see something like this though!

**Comment by rbernardino** [comment]
@RamblingCookieMonster Thanks Warren! Just making sure I'm not re-inventing the wheel. I'll dig deeper at the code to see how that will fit in most probably by extending PSDeploy.

**Comment by RamblingCookieMonster** [comment]
Closing this out for now.  If anyone has some ideas on implementation and wants to tackle this, feel free to re-open and submit a pr - cheers!
