### ISSUE TITLE
[Question] PSDeploy to PSGallery use an updated manifest version?

### ISSUE THREAD

**Issue by seanmcne** [RamblingCookieMonster/PSDeploy#81]
after testing out the psdeploy cmdlet for deploying to the PSGallery I found it does not read or use the manifest version number when publishing to the gallery.  Is there a built-in way to tell the cmdlet to read the manifest version # and use that instead of simply incrementing the minor version in the psgallery?  It doesn't appear "Version" is a valid parameter that psdeploy would understand and pass down to the psgallery deployment step.

**Comment by RamblingCookieMonster** [comment]
Hi Sean!

That's odd - do you have an example psd1 file we could see?

It might be worth modifying the PSGalleryModule dependency type to support parameter-based-gallery-metadata, I sort of assumed folks would use the psd1 and privatedata from that.  Haven't run into a case where the version from the psd1 wasn't honored, curious to see what might cause that!

Thanks!

**Comment by FooBartn** [comment]
https://github.com/FooBartn/Ucs-Puptr/blob/master/Ucs-Puptr/Ucs-Puptr.psd1

You can check mine if you like. I ran into the same thing, I just haven't had time to look into it.

**Comment by RamblingCookieMonster** [comment]
Bah!  Was hoping this was a false positive.  Thanks for the link, that should be helpful, will poke around to see what might be causing this.

**Comment by RamblingCookieMonster** [comment]
Womp!  No luck.  Any chance you could throw in $VerbosePreference='Continue' so we could see the verbose output from an attempted deployment?  If you're talking local, feel free to modify the PSGalleryModule.ps1 (in PSDeploy\PSDeployScripts) to add a whatif on Publish-Module.

Here's what I get when I did that:

```
VERBOSE: Deployments:


Source            : C:\Users\wframe\Documents\GitHub\Ucs-Puptr\Ucs-Puptr
DeploymentType    : PSGalleryModule
DeploymentOptions : {ApiKey}
Targets           : PSGallery
Tags              : 




VERBOSE: Starting deployment [Module] to PowerShell repository [PSGallery]
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Publish Location:'https://go.microsoft.com/fwlink/?LinkID=397527&clcid=0x409'.
VERBOSE: Loading module from path 'C:\Users\wframe\Documents\GitHub\Ucs-Puptr\Ucs-Puptr\Ucs-Puptr.psm1'.
VERBOSE: Module 'Ucs-Puptr' was found in 'C:\Users\wframe\Documents\GitHub\Ucs-Puptr\Ucs-Puptr'.
VERBOSE: Loading module from path 'C:\Users\wframe\AppData\Local\Temp\2133598785\Ucs-Puptr\Ucs-Puptr.psm1'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/items/psscript/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/items/psscript/FindPackagesById()?id='Ucs-Puptr'' for ''.
VERBOSE: Total package yield:'0' for the specified package 'Ucs-Puptr'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Ucs-Puptr'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'Ucs-Puptr'.
What if: Performing the operation "Publish-Module" on target "Version '1.0.45' of module 'Ucs-Puptr'".
```

Looks like it was trying to publish with the right version (also flipped through their code, I see a `Test-ModuleManifest` that seems to be how they extract the module info at a superficial glance, but might have missed something.

**Comment by RamblingCookieMonster** [comment]
Oh!  @seanmcne, are you saying it publishes, but it bumps the version number unexpectedly?  If so, [this block of code](https://github.com/seanmcne/XrmSdkPowershell_test/blob/master/BuildAndDeploy/psake.ps1#L76) in the build stage basically says 'get me the psgallery version, and bump the minor version in the psd1 itself' - if you comment out that try/catch, it should respect the version in the module manifest

Cheers!

**Comment by FooBartn** [comment]
Here's the link to it on PSGallery: https://www.powershellgallery.com/packages/ucs-puptr

When i deployed it went to version 0.0.3. If you do "install-module ucs-puptr" the psd1 that in the downloaded module has a version of 0.0.3

I have to run, but i'll add the verbose preference and have it deploy again then copy the output from appveyor.

**Comment by FooBartn** [comment]
Yup, same thing. We both copied your psake file, I believe. ^_^ I figured it was something like that, I just hadn't had time to look into it.

**Comment by seanmcne** [comment]
@RamblingCookieMonster - thx for the pointer! Is the manifest version # made available as a env variable in the scripts or is reading the manifest in the module dir probably the most direct way to accomplish that? 

Thanks for the work putting all this stuff together!

**Comment by seanmcne** [comment]
@RamblingCookieMonster - thx for the pointer! Thanks for the work putting all this stuff together!

**Comment by seanmcne** [comment]
FYI the way I'm solving this in my build process is: 

``` powershell
$vNum = (import-powershelldatafile $env:BHPSModuleManifest).ModuleVersion
$ParsedVersion = [System.Version]::Parse($vNum)
$NewVersion = "$($ParsedVersion.Major).$($ParsedVersion.Minor+1)"
Update-Metadata -Path $env:BHPSModuleManifest -PropertyName ModuleVersion -Value $NewVersion -ErrorAction stop
``` 

And if the module version was being updated/checkedin to GitHub the script would be a little simpler: 

``` powershell
$vNum = (import-powershelldatafile $env:BHPSModuleManifest).ModuleVersion
Update-Metadata -Path $env:BHPSModuleManifest -PropertyName ModuleVersion -Value $vNum -ErrorAction stop
````
