### ISSUE TITLE
Invoke-Robocopy Paths

### ISSUE THREAD

**Issue by doesitscript** [RamblingCookieMonster/PSDeploy#85]
Having trouble with the robocopy code when From is a PSDrive. At the point where Resolve-Path is called and the path's my code was using are converted, robocopy appends the new path values to the working directory causing the deploy to fail. 

Line: 
[Invoke-Robocopy#L114](https://github.com/RamblingCookieMonster/PSDeploy/blob/76dff17ffb70c613fc2fc9c0868cf9ca69668474/PSDeploy/Private/Invoke-Robocopy.ps1#L114)

Reproduce code:
```PowerShell
$LogStaging      = "$StagingDir\Logs"

# Build target deployment paths
$SystemDrives = @()
foreach ($Comp in $ComputerName) {
    New-PSDrive -Name "$($Comp.Replace(".",''))--SystemDrive" -PSProvider FileSystem -Root \\$ComputerName\C$ -Credential $LocalAdministrator
}

# Remote module paths
$LogPathDrives = Get-PSDrive | where {$_.Name -like "*--SystemDrive"} | foreach { # select -ExpandProperty Name | foreach {
    # ( "$_`:\Staging\Logs")
    Join-Path -Path $_.Root -ChildPath "Staging\Logs"
}

#PSDeploy File Code
Deploy LogScriptCollection {
    By  FileSystem LogsResults {
        FromSource $LogPathDrives
        To $LogStaging
        Tagged Prod, Logs
        WithOptions @{
            SourceIsAbsolute = $true
        }
    }
}

```

**Comment by RamblingCookieMonster** [comment]
Hi Josh!

EDIT: never mind, reproduced, was working with an old module copy that ended up in my profile psmodulepath, arg!

Seeing some odd things here as well, want to make sure we're looking at the same issue - any chance you could throw in:

* Errors message you receive, including the paths that it seems to create
* Output from Get-PSDeployment -Path \\path\to\your\deployment.ps1

Thanks!

**Comment by RamblingCookieMonster** [comment]
Hmm, @beatcracker @doesitscript - any concerns borrowing the same resolution used for the target and using it [here](https://github.com/RamblingCookieMonster/PSDeploy/blob/76dff17ffb70c613fc2fc9c0868cf9ca69668474/PSDeploy/Private/Invoke-Robocopy.ps1#L114) -   `$ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path) -replace '\\+$'`?

Seems to parse local and UNC paths without issue, am I overlooking any scenarios this would break?

**Comment by doesitscript** [comment]
That's right, it seems that when resolve-path creates a path that isn't a typical UNC path or absolute path is when Robocopy is having trouble.  Here's an example of path that would have problems.
```PowerShell
Resolve-Path \\localhost\c$
Path
----
Microsoft.PowerShell.Core\FileSystem::\\localhost\c$
```

**Comment by beatcracker** [comment]
@RamblingCookieMonster 

`GetUnresolvedProviderPathFromPSPath` returns unresolved path. I don't think we want this for source path. Maybe we could do with `GetResolvedProviderPathFromPSPath`...

@doesitscript 

> it seems that when resolve-path creates a path that isn't a typical UNC path or absolute path

Could we  use it like this?

```posh
(Resolve-Path \\localhost\c$).ProviderPath

\\localhost\c$
```

**Comment by doesitscript** [comment]
@beatcracker
This is also basically how I got things working. 
```PowerShell
(Resolve-Path \\localhost\c$).ProviderPath
\\localhost\c$
```

**Comment by RamblingCookieMonster** [comment]
Thanks all, works for me!  Anyone want to submit a PR, or shall I go ahead? Up to you : )

**Comment by RamblingCookieMonster** [comment]
Alrighty!  A little slow, but that should do it - let me know if you still run into trouble - thanks for the heads up and workaround : )
