### ISSUE TITLE
Support for Deploying Node or IISSite

### ISSUE THREAD

**Issue by mmattes** [RamblingCookieMonster/PSDeploy#92]
Hi,

i'am currently adding support for Node and IISSites to deploy some solutions. Is that of any intrest for you? If so then I will create some pull requests as soon as they are complete. 

[My Node File](https://github.com/mmattes/PSDeploy/blob/iisdeploy/PSDeploy/PSDeployScripts/Node.ps1)
[My IIS File](https://github.com/mmattes/PSDeploy/blob/iisdeploy/PSDeploy/PSDeployScripts/IISSite.ps1)

**Comment by RamblingCookieMonster** [comment]
Hiyo!

Awesome, sure, would absolutely be up for these!

What's the Node one?  Didn't see anything specific to node(.js I assume) -  Might be handy (I would use it) to make it an NSSMService (or some other name, up to you!) deployment?

Cheers!

**Comment by mmattes** [comment]
Makes sense, haven't tough of it as a general NSSMService Deployment. I will make some changes and will create a pull request then. BuT I might need help on creating proper tests as pester is new to me.

**Comment by RamblingCookieMonster** [comment]
sounds good, would be happy to help!
