### ISSUE TITLE
Filter deploy based on Tag/TagName and pre-release status

### ISSUE THREAD

**Issue by seanmcne** [RamblingCookieMonster/PSDeploy#94]
Hi, 
For our project (hosted on github) we tag releases and each release has a unique version tag. 

For instance: 
- We commit multiple fixes/changes 
- We then update & commit an updated module manifest version# (ex: v2.6) 
- We create a pre-release that's tagged (ex: v2.6) and we publish a pre-release (we don't want this published by appveyor) 
- Once we confirm the release we remove the 'draft' flag and "publish" the final tagged release on GitHub

What I'm trying to do is: 
1. Only deploy Tagged Releases on GitHub (no matter what the tag and possibly based on a portion of the tag name) 
2. Skip deployment when they're flagged as a pre-release 
3. Only deploy when there is a tag AND when it's *not* a pre-release. 

Is there a way to get the release properties (like release / pre-release) and the Tag name from GitHub?  I tried seeing if there's a way to access these properties in deploy.psdeploy.ps1? 

Thanks in advance for any pointers!

**Comment by RamblingCookieMonster** [comment]
Hello!

Interesting question - you could likely gate calling PSDeploy (or a particular deployment or deployment tag) based on APPVEYOR_REPO_TAG and APPVEYOR_REPO_TAG_NAME

Now that you mention it, I'll likely try to abstract those into BuildHelpers (e.g. BHTagName which would grab CI_COMMIT_TAG from GitLab CI, APPVEYOR_REPO_TAG_NAME from AppVeyor) - thanks for the idea : )

Might have just gone over my head, but how are you flagging something as a pre-release? via a particular version number? something in the tag name?

Cheers!

**Comment by seanmcne** [comment]
Thanks for the super quick response! 

When you create a release on github there's a checkbox (pictured below) 

![image](https://user-images.githubusercontent.com/2292260/29229411-d20c62f4-7ea3-11e7-9b25-3374bf9cc65c.png)

**Comment by seanmcne** [comment]
Interesting, your appveyor variable names helped me find some content - looks like provider settings contains most of the info: 

https://www.appveyor.com/docs/deployment/github/#provider-settings

**Comment by seanmcne** [comment]
Looking into this a bit more now, is the idea that we'd commit to Master, commit something with !Deploy and then appveyor would be responsible for tagging and releasing as part of the deployment to powershell gallery? 

Currently, we commit and commit until we're ready for a release, then we tag and draft a release to github, once we get some feedback or can test, we eventually decide to finalize the release, at that point we push out to powershell gallery (the gallery is always our final destination once we're sure we want the larger audience to easily pull down the update).

**Comment by RamblingCookieMonster** [comment]
The workflow is totally up to you, but the GitHub release part isn't covered by PSDeploy (yet) - as you notice though, AppVeyor can do that if it makes sense for you.

I work with modules that are pretty simple (from a module and release perspective) - here's my typical workflow:

* All commits end up generating a package on AppVeyor's NuGet feed [via psdeploy](https://psdeploy.readthedocs.io/en/latest/Example-AppVeyorModule-Deployment/) ([e.g.](https://github.com/RamblingCookieMonster/BuildHelpers/blob/master/Build/deploy.psdeploy.ps1#L47))
* Commits with !Deploy end up deploying to the gallery ([e.g.](https://github.com/RamblingCookieMonster/BuildHelpers/blob/master/Build/deploy.psdeploy.ps1#L20) via psdeploy)

That's about it!  I don't use tags or GitHub releases for any projects, so never got around to writing a psdeploy script for this... although now that you mention it, might be nice to have that : )

Cheers!

**Comment by seanmcne** [comment]
Thanks!  I did notice there are appveyor project settings to build tags only, I suppose I could just filter on the branch and build tags only though something to filter would be cool too.  Thanks again for the quick responses! 

<img src="https://user-images.githubusercontent.com/2292260/29345742-47dd02f8-8206-11e7-8bd7-0288d403bb08.png" width="300px"/>

**Comment by RamblingCookieMonster** [comment]
Closing this out!  If you have any ideas on things to add, feel free to open it back up - cheers!
