### ISSUE TITLE
PSGalleryModule - Make ApiKey optional

### ISSUE THREAD

**Issue by ghost** [RamblingCookieMonster/PSDeploy#97]
Similar to #72 
Can we make the ApiKey parameter optional? Some repositories do not require a key, and this blocks me from being able to publish a module to our internal repository. 

For that, the NuGetAPIKey parameter in the Publish-Module @params (Line 47 of PSGalleryModule.ps1) would need to be removed/modified. 

Any thoughts on how you'd like to proceed?

Thanks!

**Comment by devblackops** [comment]
I'm OK with making `ApiKey` an optional parameter. Thoughts @RamblingCookieMonster?

@commanderpoop, would you like to put in a PR with the changes?

**Comment by RamblingCookieMonster** [comment]
Thanks for the ping @devblackops!

@commanderpoop - makes sense to me, if you're up for a pull request, that would be awesome!  Maybe just remove mandatory param attribute, conditionally add to params hash?

Cheers!

**Comment by ghost** [comment]
Here you go! #99 

@RamblingCookieMonster @devblackops

**Comment by RamblingCookieMonster** [comment]
Closing this out, thanks for submitting the PR!
